data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          imsize: 768
          dirnames:
            - '''/extdata/ocr/phungpx/projects/PHUNGPX/object_detection_pytorch/efficient_det_pytorch/dataset/EPASS/train'''
            - '''/extdata/ocr/phungpx/projects/PHUNGPX/object_detection_pytorch/efficient_det_pytorch/dataset/EPASS/valid'''
            - '''/extdata/ocr/phungpx/projects/PHUNGPX/object_detection_pytorch/efficient_det_pytorch/dataset/EPASS/test'''
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.json''']
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            EPASS_TYPE_1: 0
            EPASS_TYPE_2: 1
            EPASS_TYPE_3: 2
            EPASS_TYPE_4: 3
            EPASS_TYPE_5: 4
      batch_size: 4
      shuffle: False
      num_workers: 12
      pin_memory: True
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.retina_net
  class: Model
  Model:
    num_classes: 5
    backbone_name: '''resnet50'''
    backbone_pretrained: False
    scales: ['2 ** 0', '2 ** (1 / 3)', '2 ** (2 / 3)']
    aspect_ratios: [0.25, 0.5, 1., 2., 4.]  # anchor_width / anchor_height
    iou_threshold: 0.2
    score_threshold: 0.5

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.evaluator
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.core.metric.mAP
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                EPASS_TYPE_1: 0
                EPASS_TYPE_2: 1
                EPASS_TYPE_3: 2
                EPASS_TYPE_4: 3
                EPASS_TYPE_5: 4
              iou_threshold: 0.5
              method: '''every_point_interpolation'''
              print_FP_files: False
          output_transform: 'lambda x: (x[0], x[1], x[2])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/EPASS/resnet50_5_classes/'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/EPASS/resnet50_5_classes/'''
    imsize: 768
    classes:
      EPASS_TYPE_1: [[128, 0, 0], 0]
      EPASS_TYPE_2: [[0, 128, 0], 1]
      EPASS_TYPE_3: [[128, 128, 0], 2]
      EPASS_TYPE_4: [[0, 0, 128], 3]
      EPASS_TYPE_5: [[128, 0, 128], 4]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.evaluator
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
